export const data = [
  {
    event_title: "Bootcamper Meet Up",
    date: "2023-11-11",
    time: "14:00",
    location: "Subway - FooBar Street - Gloucester - UK",
    event_type: "Social",
    attendees: 30,
  },
  {
    event_title: "Junior Devs Networking",
    date: "2023-10-27",
    time: "19:00",
    location: "Room 3 - Saint Philip's Place - Birmingham - UK",
    event_type: "Tech",
    attendees: 5,
  },
  {
    event_title: "Bootcamper Meet Up",
    date: "2023-12-23",
    time: "19:00",
    location: "Bussey Building - Peckham - London - UK",
    event_type: "Social",
    attendees: 15,
  },
  {
    event_title: "Introduction to ReactJS",
    date: "2024-01-26",
    time: "10:00",
    location: "Meeting Room 1 - Zoom - Online Interface - The Internet",
    event_type: "Online",
    attendees: 7,
  },
  {
    event_title: "Manchester Tech Festival",
    date: "2023-10-30",
    time: "09:00",
    location: "Victoria Baths - Hathersage Rd - Manchester - UK",
    event_type: "Tech",
    attendees: 7,
  },
  {
    event_title: "Pathways into Tech",
    date: "2023-10-30",
    time: "08:30",
    location: "No1 Circle Square - Symphony Square - Manchester - UK",
    event_type: "Tech",
    attendees: 13,
  },
  {
    event_title: "Tech Wednesday",
    date: "2023-11-15",
    time: "17:30",
    location: "Meeting Room 4 - Zoom - Online Interface - The Internet",
    event_type: "Online",
    attendees: 5,
  },
  {
    event_title: "Bootcamper Meet Up",
    date: "2023-12-23",
    time: "19:00",
    location: "Cunard Building - Liverpool Waterfront - Liverpool - UK",
    event_type: "Social",
    attendees: 15,
  },
];
